### ISSUE TITLE
Unable to open site, issue at Prerendring

### ISSUE THREAD

**Issue by gomjabar6** [EdCharbeneau/kuiWithAngularDotnet#1]
Followed instructions at https://www.telerik.com/blogs/cooking-with-aspnet-core-and-angular-2 on my own project and found an error.
Then I tracked down this GitHub project hoping that the issue was something in my project, followed the read me instructions to the letter, produced same error.

Error Description:
When navigating to the site an unhanded exception occurs when processing the request: 

> NodeInvocationException:
>  Prerendering failed because of error: ReferenceError: document is not defined
> at C:\Users\GarrettCurtis\Desktop\kuiWithAngularDotnet-master\KuiWithAngularDotnet\ClientApp\dist\main-server.js:639:30
> at content (C:\Users\GarrettCurtis\Desktop\kuiWithAngularDotnet-master\KuiWithAngularDotnet\ClientApp\dist\main-server.js:7679:13)

Debugging this error leads me to believe the error is in the `@progress/kendo-angular-grid` package since removing this package form the module imports removes the error (of course then I get an error about the kendo-grid module properties not being defined).

Following the stack reveals that the error stems from this line, which seems to be part of the calendar date picker for the grid componenet:
`var CALENDAR_ELEMENT_MONTH = calendar(view(content(6), 'k-calendar-view k-calendar-monthview'));`
which, in turn, tries to create a table:
`var content = function (rows) { return (table([
    tbody([
        tr([th('1')]) ...`
 and invokes the DOM:
`var th = util_1.domContainerFactory('th');,`
which we don't have during pre-rendering, thus spitting out the error

Clearly this is a major issue with the Angular Grid module in the context of ASP.NET Core sites. I guess that this wasn't an issue previously and there was some major change somewhere that created it. Unfortunately I can't track down any mention of this anywhere. hopefully you have more luck. 

Environment:
- ASP.NET Core 2.0
-   npm: '3.10.10',
-   ares: '1.10.1-DEV',
-   http_parser: '2.7.0',
-   icu: '58.2',
-   modules: '48',
-   node: '6.11.4',
-   openssl: '1.0.2l',
-   uv: '1.11.0',
-   v8: '5.1.281.108',
-   zlib: '1.2.11'

**Comment by EdCharbeneau** [comment]
Sorry for the delay. I've been traveling with limited network access. Let me see if I can recreate the issue and we'll go from there. Thanks for the detailed write up.

**Comment by EdCharbeneau** [comment]
I can reproduce the error. I'm going to post the issue on the main Kendo UI repository so it can be investigated further.

**Comment by gomjabar6** [comment]
Thanks for the update, hopefully they can get this cleared up!

**Comment by EdCharbeneau** [comment]
You can see the issue at https://github.com/telerik/kendo-angular/issues/1033 Let's continue the conversation there.

**Comment by gomjabar6** [comment]
Cleaned up via the date package update to 1.3.1, [linked here](https://github.com/telerik/kendo-angular/issues/1031)
This example project is working again!

**Comment by EdCharbeneau** [comment]
Awesome, glad to hear it!
